### ISSUE TITLE
Allow Exhibition display in an existing navigation stack

### ISSUE THREAD

**Issue by IanHoar** [mjarvis/Exhibition#34]
When pushing Exhibition in a navigation stack a double navigation bar is visible due to the nested `NavigationView`. Would be nice to have some way to indicate to the lib that the extra navigation view was not required.

<img width="449" alt="Screen Shot 2022-02-28 at 12 54 29 PM" src="https://user-images.githubusercontent.com/967712/156057180-90d9cc4e-caf7-480c-a749-faaf51d6fbfb.png">

**Comment by mjarvis** [comment]
Navigation and display is something I'd like to have customizable.
More than just specifying whether or not its in a navigation view already.

I'd like to consider the whole picture with this.
What if the consumer doesn't want a navigation view? and instead wants some custom navigation into exhibits?

The `layout` closure on Exhibit provides a small portion of this, but is not as clear as I'd like.

How do we allow for customization of that level as well.

Potentially:
- Move navigation code into the Sourcery template.
- Provide closures / bindings instead of performing navigation inline

**Comment by mjarvis** [comment]
On the other side, one could say this is not meant to be an integrated view inside of another app. It should be presented in such a way that it has complete control over the viewport. EG: Presentation, new window, etc.

Similar to how storyboard is its own separate webpage, and not an integrated portion.

**Comment by mjarvis** [comment]
Resolved by #39 

You can now remove the navigation view from the sourcery template and push onto your own stack.
